language: elixir
services:
  - postgresql
addons:
    postgresql: "9.6"
elixir:
  - 1.5.0
otp_release:
  - 20.0
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build/
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - mix do ecto.create, ecto.migrate
script:
  - mix credo
  - mix test
