---

github_keys_create_install_user: false
github_keys_install_user: deploy
github_keys_github_users:
  - oestrich

postgresql_version: 10
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_cluster_name: "main"
postgresql_cluster_reset: false
postgresql_default_auth_method: "trust"

postgresql_users:
  - name: deploy

postgresql_user_privileges:
  - name: deploy
    role_attr_flags: "SUPERUSER"

postgresql_databases:
  - name: exventure
    owner: deploy
    encoding: "UTF-8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"

firewall_ports:
  - rule: allow
    port: http
  - rule: allow
    port: https
  - rule: allow
    port: ssh
  - rule: allow
    port: 5555
  - rule: allow
    port: 5443

node_exporter_version: "0.17.0"
node_exporter_checksum: "d2e00d805dbfdc67e7291ce2d2ff151f758dd7401dd993411ff3818d0e231489"
